CREATE ROLE me WITH
SUPERUSER
CREATEDB
NOCREATEROLE
NOINHERIT
LOGIN
NOREPLICATION
NOBYPASSRLS
CONNECTION LIMIT -1;


-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "user" (
    id SERIAL PRIMARY KEY,
    username character varying(80) NOT NULL UNIQUE,
    password character varying(1000) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_pkey ON "user"(id int4_ops);
CREATE UNIQUE INDEX user_username_key ON "user"(username text_ops);


-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE teams (
    id character varying(20) PRIMARY KEY,
    full_name character varying(60) NOT NULL UNIQUE,
    city character varying(30) NOT NULL,
    nickname character varying(30) NOT NULL,
    abbreviated character varying(10),
    competition character varying(10),
    sports_api_id integer
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX teams_full_name_key ON teams(full_name text_ops);
CREATE UNIQUE INDEX teams_pkey ON teams(id text_ops);



-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE competitions (
    api_key character varying(60) PRIMARY KEY,
    title character varying(20) NOT NULL UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX competitions_pkey ON competitions(api_key text_ops);
CREATE UNIQUE INDEX competitions_title_key ON competitions(title text_ops);



-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE bookmakers (
    api_key character varying(60) PRIMARY KEY,
    title character varying(60) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX bookmakers_pkey ON bookmakers(api_key text_ops);



-- DDL generated by Postico 1.5.22

-- Not all database features are supported. Do not use for backup.



-- Table Definition ----------------------------------------------



CREATE TABLE games (

    id character varying(200) PRIMARY KEY,

    home_team character varying NOT NULL,

    away_team character varying NOT NULL,

    commence_time timestamp without time zone NOT NULL,

    competition character varying(100) NOT NULL

);



-- Indices -------------------------------------------------------



CREATE UNIQUE INDEX games_pkey ON games(id text_ops);



-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE markets (
    id SERIAL PRIMARY KEY,
    bookmaker character varying(60) NOT NULL,
    game_id character varying(100) NOT NULL REFERENCES games(id),
    outcome character varying(60) NOT NULL,
    market character varying(20) NOT NULL,
    point numeric,
    price numeric NOT NULL,
    last_update timestamp without time zone NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX markets_pkey ON markets(id int4_ops);



-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE contests (
    id SERIAL PRIMARY KEY,
    type character varying(25) NOT NULL,
    nfl boolean NOT NULL,
    ncaa_fb boolean NOT NULL,
    nba boolean NOT NULL,
    wnba boolean NOT NULL,
    ncaa_mbb boolean NOT NULL,
    ncaa_wbb boolean NOT NULL,
    mlb boolean NOT NULL,
    nhl boolean NOT NULL,
    epl boolean NOT NULL
    spreads boolean NOT NULL,
    h2h boolean NOT NULL,
    over_under boolean NOT NULL,
    contest_start timestamp without time zone NOT NULL,
    period_duration interval,
    period_count integer,
    period_fund numeric,
    max_users integer,
    max_entries integer,
    max_user_entries integer,
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX contests_pkey ON contests(id int4_ops);




-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE entries (
    id SERIAL PRIMARY KEY,
    name character varying(100),
    funds integer NOT NULL,
    default_entry boolean NOT NULL,
    user_id integer REFERENCES "user"(id),
    contest_id integer REFERENCES contests(id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX entries_pkey ON entries(id int4_ops);



-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE bets (
    id SERIAL PRIMARY KEY,
    user_id integer NOT NULL REFERENCES "user"(id),
    market_id integer NOT NULL REFERENCES markets(id),
    wager numeric NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX bets_pkey ON bets(id int4_ops);