const utilities = {
    addAmericanPrice: require("./odds/addAmericanPrice"),
    addToBetslip: require("./odds/addToBetslip"),
    convertToAmerican: require("./odds/convertToAmerican"),
    findWinner: require("./scores/findWinner"),
    fixTimestamp: require("./dateTime/fixTimestamp"),
    formatMarket: require("./odds/formatMarket"),
    formattedResponse: require("./formattedResponse"),
    formatTimestamp: require("./dateTime/formatTimestamp"),
    getAvailableOddsCellText: require("./odds/getAvailableOddsCellText"),
    getBetPointsText: require("./userBets/getBetPointsText"),
    getDate: require("./dateTime/getDate"),
    getPoint: require("./odds/getPoint"),
    getTime: require("./dateTime/getTime"),
    getUpdateScoreQueryText: require("./scores/getUpdateScoreQueryText"),
    getUpdateScoreQueryValues: require("./scores/getUpdateScoreQueryValues"),
    isDateString: require("./dateTime/isDateString"),
    isEntryMatch: require("./isEntryMatch"),
    isFinished: require("./isFinished"),
    makeDateString: require("./dateTime/makeDateString"),
    makeGameID: require("./makeGameID"),
    makeGamesArray: require("./makeGamesArray"),
    makeLines: require("./odds/makeLines"),
    matchGamesToMarkets: require("./odds/matchGamesToMarkets"),
    noActiveBets: require("./userBets/noActiveBets"),
    removeSpaces: require("./removeSpaces")
}
module.exports = utilities;