const utilities = {
    addToBetslip: require("./addToBetslip"),
    convertToAmerican: require("./convertToAmerican"),
    findWinner: require("./findWinner"),
    fixTimestamp: require("./dateTime/fixTimestamp"),
    formattedResponse: require("./formattedResponse"),
    formatTimestamp: require("./dateTime/formatTimestamp"),
    getAvailableOddsCellText: require("./getAvailableOddsCellText"),
    getBetPointsText: require("./getBetPointsText"),
    getDate: require("./dateTime/getDate"),
    getTime: require("./dateTime/getTime"),
    getUpdateScoreQueryText: require("./getUpdateScoreQueryText"),
    getUpdateScoreQueryValues: require("./getUpdateScoreQueryValues"),
    isDateString: require("./dateTime/isDateString"),
    isEntryMatch: require("./isEntryMatch"),
    isFinished: require("./isFinished"),
    makeDateString: require("./dateTime/makeDateString"),
    makeGameID: require("./makeGameID"),
    makeGamesArray: require("./makeGamesArray"),
    makeLines: require("./makeLines"),
    matchGamesToMarkets: require("./matchGamesToMarkets"),
    noActiveBets: require("./noActiveBets"),
    removeSpaces: require("./removeSpaces")
}
module.exports = utilities;